server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jjim
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  application:
    admin:
      jmx-name:
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  token:
    secret: hIVZQaKeZ3Vn9+N33AxllGw5Bm+T8Q9G4KID7FHAAaCPTQtQmuS589mELaXfjUY08x7dkhCiiYfpIhtN/vphoQ==